import type { Lesson } from "./types";

export const aiForLearning: Lesson = {
  introduction: `
For centuries, people have learned through books, teachers and personal experience. Today, Artificial Intelligence is adding a completely new way to learn.

AI is not replacing teachers or traditional education. Instead, it acts as a personal learning assistant that is available anytime, anywhere.

Unlike a textbook, AI can adapt to your questions.

Unlike a video, AI can explain the same concept in multiple ways.

Unlike a search engine, AI can combine information into a clear and personalized explanation.

Whether you're learning mathematics, programming, languages, science or history, AI can make learning more interactive, engaging and efficient.

However, using AI effectively requires more than simply asking it for answers.

The goal should never be to let AI think for you.

The goal is to use AI to understand concepts faster, practice more effectively and become a more independent learner.

When used correctly, AI becomes one of the most powerful educational tools ever created.
`,
  whyItMatters: `
Learning is one of the most valuable skills you will ever develop.

The faster and better you learn, the easier it becomes to adapt to new technologies, careers and opportunities.

AI helps remove many common obstacles to learning.

For example, it can:

* Explain difficult topics.
* Answer follow-up questions.
* Generate quizzes.
* Summarize long articles.
* Translate information.
* Create study plans.
* Recommend learning resources.

Instead of replacing your effort, AI amplifies it.

The students who learn how to study with AI—not copy from AI—will have a significant advantage in the future.
`,
  keyPrinciples: `
### 1. Use AI to understand, not to copy.

One of the biggest mistakes learners make is asking AI to complete assignments for them.

This may save time in the short term, but it prevents real learning.

Instead, ask AI to explain concepts until you truly understand them.

Learning happens when your understanding grows—not when answers are copied.

---

### 2. Ask follow-up questions.

One of AI's greatest strengths is conversation.

If you don't understand an explanation, ask:

* Can you simplify it?
* Can you give another example?
* Can you explain it visually?
* Can you compare it to something I already know?

Every follow-up question improves your understanding.

---

### 3. Learn actively.

Reading an explanation isn't enough.

Use AI to create:

* Practice questions.
* Flashcards.
* Quizzes.
* Real-world examples.
* Small exercises.

Active learning helps move information into long-term memory.

---

### 4. Personalize your learning.

Everyone learns differently.

AI can adjust explanations based on your needs.

For example:

* Explain this to a beginner.
* Explain this like I'm 12 years old.
* Explain it using sports examples.
* Explain it with coding analogies.
* Give me a visual comparison.

The ability to personalize learning is one of AI's greatest advantages.

---

### 5. Verify and think critically.

AI is an excellent teacher, but it is not perfect.

Sometimes it makes mistakes.

Always question information.

Cross-check important facts with trusted books, official documentation or reliable educational sources.

Critical thinking remains your most valuable skill.
`,
  examples: `
### Example 1 — Learning Programming

Instead of copying code generated by AI, ask:

*"Explain every line of this code and why it works."*

You'll build real understanding rather than memorizing syntax.

---

### Example 2 — Studying for an Exam

Upload your notes and ask AI to:

* Summarize key concepts.
* Create flashcards.
* Generate multiple-choice questions.
* Test your understanding.

This transforms passive reading into active studying.

---

### Example 3 — Learning a Language

Ask AI to:

* Correct your grammar.
* Hold conversations.
* Explain vocabulary.
* Create quizzes.
* Simulate real-life situations.

You receive instant feedback without waiting for a teacher.

---

### Example 4 — Understanding Science

If a scientific concept feels difficult, ask AI to explain it at different levels.

For example:

* Beginner.
* High school.
* University.
* Professional.

This flexibility makes difficult topics much easier to understand.
`,
  commonMistakes: `
### Letting AI do all the work.

If AI writes every answer, solves every problem and completes every assignment, you aren't learning.

Use AI to guide your thinking—not replace it.

---

### Accepting explanations without questioning them.

AI can be wrong.

Always verify important concepts and compare explanations with trusted educational resources.

---

### Only reading answers.

Real learning requires practice.

Ask AI to create exercises, quizzes and challenges that force you to apply what you've learned.

---

### Asking vague questions.

Questions like:

*"Teach me coding."*

are too broad.

Instead, ask:

*"Explain variables in JavaScript using simple real-world examples."*

Specific questions produce better learning experiences.
`,
  exercises: `
## Exercise 1 — Learn Something New

Choose a topic you've never studied before.

Ask AI to explain it in simple language.

Then ask three follow-up questions until you fully understand it.

---

## Exercise 2 — Create Your Own Quiz

Study a topic for 20 minutes.

Then ask AI to generate:

* 10 multiple-choice questions.
* 5 short-answer questions.
* 2 real-world scenarios.

Answer everything without looking at your notes.

---

## Exercise 3 — Teach the AI Back

After learning a topic, explain it back to the AI in your own words.

Ask:

*"Can you identify anything I misunderstood?"*

Teaching is one of the best ways to strengthen your understanding.

---

## Exercise 4 — Reflection

Answer these questions:

* How has AI changed the way I learn?
* When should I rely on AI?
* When should I study independently?
* What habits will help me become a better learner?
`,
  summary: `
AI is one of the most powerful learning tools ever created.

It can explain, personalize, quiz and guide your learning in ways that traditional resources cannot.

However, AI should support your education—not replace it.

The most successful learners use AI to:

* Understand concepts.
* Practice consistently.
* Ask better questions.
* Receive instant feedback.
* Think more critically.

Remember:

**Learning isn't about getting answers.**

**Learning is about developing understanding.**

AI can accelerate that process, but your curiosity, effort and critical thinking remain the most important parts of your education.
`,
  resources: `
### Recommended Books

* *Make It Stick* — Peter C. Brown
* *Ultralearning* — Scott H. Young
* *A Mind for Numbers* — Barbara Oakley
* *Co-Intelligence* — Ethan Mollick

### Practical Resources

* Khan Academy
* Coursera
* edX
* DeepLearning.AI
* MIT OpenCourseWare
* OpenAI

### Challenge

For the next **7 days**, use AI as your personal tutor instead of your answer machine.

Every day:

* Learn one new concept.
* Ask at least **five follow-up questions**.
* Complete a quiz created by AI.
* Explain the topic back in your own words.
* Identify one thing you still don't understand.

By the end of the week, you'll notice that AI isn't most valuable because it gives answers—it's most valuable because it helps you ask **better questions** and build **deeper understanding**.
`,
};
